name: Nix CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-with-docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run health checks with Docker
      run: ./enter-nix checkhealth

  build-with-podman:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Podman
      run: |
        sudo apt-get update
        sudo apt-get install -y podman

    - name: Run health checks with Podman
      run: ./enter-nix checkhealth
